Update container images to v0.10.1

diff --git a/application.yaml b/application.yaml
--- a/application.yaml
+++ b/application.yaml
@@ -27,32 +27,22 @@ spec:
       - env:
         - name: PORT
           value: "9555"
-        image: gcr.io/google-samples/microservices-demo/adservice:v0.5.0
+        image: gcr.io/google-samples/microservices-demo/adservice:v0.10.1
         imagePullPolicy: IfNotPresent
         livenessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:9555
-          failureThreshold: 3
           initialDelaySeconds: 20
           periodSeconds: 15
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 9555
         name: server
         ports:
         - containerPort: 9555
           protocol: TCP
         readinessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:9555
-          failureThreshold: 3
           initialDelaySeconds: 20
           periodSeconds: 15
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 9555
         resources:
           limits:
             cpu: 300m
@@ -107,34 +97,21 @@ spec:
       - env:
         - name: REDIS_ADDR
           value: redis-cart:6379
-        image: gcr.io/google-samples/microservices-demo/cartservice:v0.5.0
+        image: gcr.io/google-samples/microservices-demo/cartservice:v0.10.1
         imagePullPolicy: IfNotPresent
         livenessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:7070
-            - -rpc-timeout=5s
-          failureThreshold: 3
           initialDelaySeconds: 15
           periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 7070
         name: server
         ports:
         - containerPort: 7070
           protocol: TCP
         readinessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:7070
-            - -rpc-timeout=5s
-          failureThreshold: 3
           initialDelaySeconds: 15
-          periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 7070
         resources:
           limits:
             cpu: 300m
@@ -201,30 +178,18 @@ spec:
           value: currencyservice:7000
         - name: CART_SERVICE_ADDR
           value: cartservice:7070
-        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.5.0
+        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.10.1
         imagePullPolicy: IfNotPresent
         livenessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:5050
-          failureThreshold: 3
-          periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
+            grpc:
+              port: 5050
         name: server
         ports:
         - containerPort: 5050
           protocol: TCP
         readinessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:5050
-          failureThreshold: 3
-          periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
+            grpc:
+              port: 5050
         resources:
           limits:
             cpu: 200m
@@ -280,31 +245,19 @@ spec:
           value: "7000"
         - name: DISABLE_PROFILER
           value: "1"
-        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.5.0
+        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.10.1
         imagePullPolicy: IfNotPresent
         livenessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:7000
-          failureThreshold: 3
-          periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 7000
         name: server
         ports:
         - containerPort: 7000
           name: grpc
           protocol: TCP
         readinessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:7000
-          failureThreshold: 3
-          periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 7000
         resources:
           limits:
             cpu: 200m
@@ -360,30 +313,19 @@ spec:
           value: "50051"
         - name: DISABLE_PROFILER
           value: "1"
-        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.5.0
+        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.10.1
         imagePullPolicy: IfNotPresent
         livenessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:50051
-          failureThreshold: 3
-          periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 50051
         name: server
         ports:
         - containerPort: 50051
           protocol: TCP
         readinessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:50051
-          failureThreshold: 3
           periodSeconds: 5
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 50051
         resources:
           limits:
             cpu: 200m
@@ -439,30 +381,20 @@ spec:
           value: "8080"
         - name: DISABLE_PROFILER
           value: "1"
-        image: gcr.io/google-samples/microservices-demo/emailservice:v0.5.0
+        image: gcr.io/google-samples/microservices-demo/emailservice:v0.10.1
         imagePullPolicy: IfNotPresent
         livenessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:8080
-          failureThreshold: 3
           periodSeconds: 5
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 8080
         name: server
         ports:
         - containerPort: 8080
           protocol: TCP
         readinessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:8080
-          failureThreshold: 3
           periodSeconds: 5
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 8080
         resources:
           limits:
             cpu: 200m
@@ -533,9 +465,11 @@ spec:
           value: checkoutservice:5050
         - name: AD_SERVICE_ADDR
           value: adservice:9555
+        - name: SHOPPING_ASSISTANT_SERVICE_ADDR
+          value: "shoppingassistantservice:80"
         - name: ENABLE_PROFILER
           value: "0"
-        image: gcr.io/google-samples/microservices-demo/frontend:v0.5.0
+        image: gcr.io/google-samples/microservices-demo/frontend:v0.10.1
         imagePullPolicy: IfNotPresent
         livenessProbe:
           failureThreshold: 3
@@ -625,7 +559,7 @@ spec:
           value: frontend:80
         - name: USERS
           value: "10"
-        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.5.0
+        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.10.1
         imagePullPolicy: IfNotPresent
         name: main
         resources:
@@ -650,12 +584,20 @@ spec:
         - /bin/sh
         - -exc
         - |
-          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
-          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
-          if test $STATUSCODE -ne 200; then
-              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-              exit 1
-          fi
+          MAX_RETRIES=12
+          RETRY_INTERVAL=10
+          for i in $(seq 1 $MAX_RETRIES); do
+            echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
+            STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+            if [ $STATUSCODE -eq 200 ]; then
+                echo "Frontend is reachable."
+                exit 0
+            fi
+            echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+            sleep $RETRY_INTERVAL
+          done
+          echo "Failed to reach frontend after $MAX_RETRIES attempts."
+          exit 1
         env:
         - name: FRONTEND_ADDR
           value: frontend:80
@@ -710,30 +652,18 @@ spec:
           value: "50051"
         - name: DISABLE_PROFILER
           value: "1"
-        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.5.0
+        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.10.1
         imagePullPolicy: IfNotPresent
         livenessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:50051
-          failureThreshold: 3
-          periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 50051
         name: server
         ports:
         - containerPort: 50051
           protocol: TCP
         readinessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:50051
-          failureThreshold: 3
-          periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 50051
         resources:
           limits:
             cpu: 200m
@@ -789,30 +719,18 @@ spec:
           value: "3550"
         - name: DISABLE_PROFILER
           value: "1"
-        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.5.0
+        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.10.1
         imagePullPolicy: IfNotPresent
         livenessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:3550
-          failureThreshold: 3
-          periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 3550
         name: server
         ports:
         - containerPort: 3550
           protocol: TCP
         readinessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:3550
-          failureThreshold: 3
-          periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 3550
         resources:
           limits:
             cpu: 200m
@@ -871,30 +789,20 @@ spec:
           value: productcatalogservice:3550
         - name: DISABLE_PROFILER
           value: "1"
-        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.5.0
+        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.10.1
         imagePullPolicy: IfNotPresent
         livenessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:8080
-          failureThreshold: 3
           periodSeconds: 5
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 8080
         name: server
         ports:
         - containerPort: 8080
           protocol: TCP
         readinessProbe:
-          exec:
-            command:
-            - /bin/grpc_health_probe
-            - -addr=:8080
-          failureThreshold: 3
           periodSeconds: 5
-          successThreshold: 1
-          timeoutSeconds: 1
+          grpc:
+            port: 8080
         resources:
           limits:
             cpu: 200m
diff --git a/kubernetes-manifests/deployment-loadgenerator.yaml b/kubernetes-manifests/deployment-loadgenerator.yaml
--- a/kubernetes-manifests/deployment-loadgenerator.yaml
+++ b/kubernetes-manifests/deployment-loadgenerator.yaml
@@ -32,7 +32,7 @@ spec:
           value: frontend:80
         - name: USERS
           value: "10"
-        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.5.0
+        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.10.1
         imagePullPolicy: IfNotPresent
         name: main
         resources:
@@ -57,12 +57,20 @@ spec:
         - /bin/sh
         - -exc
         - |
-          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
-          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
-          if test $STATUSCODE -ne 200; then
-              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-              exit 1
-          fi
+          MAX_RETRIES=12
+          RETRY_INTERVAL=10
+          for i in $(seq 1 $MAX_RETRIES); do
+            echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
+            STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+            if [ $STATUSCODE -eq 200 ]; then
+                echo "Frontend is reachable."
+                exit 0
+            fi
+            echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+            sleep $RETRY_INTERVAL
+          done
+          echo "Failed to reach frontend after $MAX_RETRIES attempts."
+          exit 1
         env:
         - name: FRONTEND_ADDR
           value: frontend:80
